name: Automated npm dedupe

on:
  issue_comment:
    types:
      - created
  schedule:
    - cron: 46 6 * * *
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  npm-dedupe:
    name: npm dedupe

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64

    runs-on: ${{ matrix.os }}
    environment: automated
    timeout-minutes: 10

    if: >-
      github.event_name != 'issue_comment' || (startsWith(github.event.issue.title, 'Automated npm dedupe') && contains(github.event.comment.body,
      '/rerun'))

    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: 1248576
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      - name: Setup pnpm
        run: corepack enable

      - name: Get pnpm cache directory
        shell: bash
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_ENV}

      - name: Use pnpm cache
        uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ matrix.os }}-${{ matrix.arch }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.arch }}-node-

      - name: Install pnpm dependencies
        id: install-pnpm
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile
        continue-on-error: true

      - name: Install pnpm dependencies (retry)
        if: steps.install-pnpm.outcome == 'failure'
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile

      - name: Run pnpm dedupe
        run: |
          set -o pipefail
          pnpm dedupe 2>&1 | tee .github/update.log || true
          sed -e 's/\x1b\[[0-9;]*m//g' .github/update.log > .github/pr_body.log

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push to branch
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          default_author: github_actions
          message: Automated npm dedupe
          new_branch: automated/npm-dedupe
          push: origin automated/npm-dedupe --set-upstream --force

      - name: Create pull request
        if: env.changes == 'true'
        run: |-
          if [[ $(gh pr view automated/npm-dedupe --json state --jq .state || true) != "OPEN" ]]; then
            gh pr create \
              --head automated/npm-dedupe \
              --title "Automated npm dedupe" \
              --body-file .github/pr_body.log \
              --label automated
          else
            gh pr edit automated/npm-dedupe \
              --title "Automated npm dedupe" \
              --body-file .github/pr_body.log
          fi

          gh pr merge --auto --squash --delete-branch automated/npm-dedupe
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Close pull request
        if: env.changes == 'false'
        run: gh pr list --head automated/npm-dedupe --json number --jq '.[].number' | xargs -rn1 gh pr close --delete-branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
