name: Automated trunk upgrade

on:
  issue_comment:
    types:
      - created
  push:
    branches:
      - main
    paths:
      - .trunk/**
  schedule:
    - cron: 2 6 * * *
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  trunk-upgrade:
    name: trunk upgrade

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64

    runs-on: ${{ matrix.os }}
    environment: automated
    timeout-minutes: 10

    if: >-
      github.event_name != 'issue_comment' || (startsWith(github.event.issue.title, 'Automated trunk upgrade') && contains(github.event.comment.body,
      '/rerun'))

    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: 1248576
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      - name: Setup pnpm
        run: corepack enable

      - name: Get pnpm cache directory
        shell: bash
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_ENV}

      - name: Use pnpm cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ${{ matrix.os }}-${{ matrix.arch }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.arch }}-node-

      - name: Install pnpm dependencies
        id: install-pnpm
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile
        continue-on-error: true

      - name: Install pnpm dependencies (retry)
        if: steps.install-pnpm.outcome == 'failure'
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile

      - name: Set up Trunk
        run: curl https://get.trunk.io -fsSL | bash -s -- -y

      - name: Trunk upgrade
        run: |
          set -o pipefail
          trunk upgrade --yes-to-all --no-progress --ci --color | tee .github/update.log
          sed -e '/Downloading Trunk/,/Unpacking Trunk... done/d' -e 's/\x1b\[[0-9;]*m//g' -e 's/^\(  \)\{0,1\}  /\1- /' .github/update.log > .github/pr_body.log
          perl -0777 -ne 'print join ", ", map {s/://gr} map {s/^- //r} grep {/^(-|cli) /} split "\n"' .github/pr_body.log > .github/pr_title.log

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Trunk Check
        if: env.changes == 'true'
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
        with:
          check-mode: all
        continue-on-error: true

      - name: Commit and push to branch
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          default_author: github_actor
          message: Automated trunk upgrade [skip ci]
          new_branch: automated/trunk-upgrade
          fetch: false
          push: origin automated/trunk-upgrade --set-upstream --force

      - name: Create pull request
        if: env.changes == 'true'
        run: |-
          if [[ $(gh pr view automated/trunk-upgrade --json state --jq .state || true) != "OPEN" ]]; then
            gh pr create \
              --head automated/trunk-upgrade \
              --title "Automated trunk upgrade $(cat .github/pr_title.log) [skip ci]" \
              --body-file .github/pr_body.log \
              --label automated \
              --label trunk
          else
            gh pr edit automated/trunk-upgrade \
              --title "Automated trunk upgrade $(cat .github/pr_title.log) [skip ci]" \
              --body-file .github/pr_body.log
          fi

          gh pr merge --admin --squash --delete-branch automated/trunk-upgrade
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Close pull request
        if: env.changes == 'false'
        run: gh pr list --head automated/trunk-upgrade --json number --jq '.[].number' | xargs -rn1 gh pr close --delete-branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
